import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { cn } from "@/lib/utils";
import Header from "./components/Header";
import AuthInit from "./components/AuthInit";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Devoverflow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={cn(inter.className, "dark:bg-black dark:text-white")}>
        <AuthInit />
        <Header />
        {children}
      </body>
    </html>
  );
}
